# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieMania' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieMania

  pod 'IQKeyboardManager'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Cosmos'
  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.2'
  target 'MovieManiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieManiaUITests' do
    # Pods for testing
  end

end
